"""
World packs: the whole of a game world as one portable JSON file.

A pack contains *content* — monsters, items, spells, the level curve, drops, towns,
vendors and the control row. It deliberately contains no player data (characters,
bags, forum posts, explored tiles), so importing a pack swaps the world out from
under the players without deleting them.

The format is plain, readable JSON with explicit field names, so a pack can be
hand-edited or generated by other tools — that's the point of it.
"""
import json
from datetime import datetime, timezone

from django.db import transaction

from .models import (Drop, GameControl, Item, LevelTier, Monster, Spell, Town,
                     TownSection, Vendor)

FORMAT = "dragon-knight-world"
VERSION = 1


# ── export ──────────────────────────────────────────────────────────────────
def _row(obj, fields):
    return {f: getattr(obj, f) for f in fields}


MONSTER_FIELDS = ["id", "name", "max_hp", "max_damage", "armor", "level",
                  "max_exp", "max_gold", "immune"]
ITEM_FIELDS = ["id", "slot", "name", "buy_cost", "power", "special"]
SPELL_FIELDS = ["id", "name", "mp_cost", "effect", "attribute"]
DROP_FIELDS = ["id", "name", "min_monster_level", "drop_type", "attribute1", "attribute2"]
LEVEL_FIELDS = ["char_class", "level", "exp_required", "hp_gain", "mp_gain", "tp_gain",
                "strength_gain", "dexterity_gain"]
TOWN_FIELDS = ["id", "name", "latitude", "longitude", "inn_price", "map_price",
               "travel_points"]
VENDOR_FIELDS = ["id", "name", "slug", "kind", "blurb", "sort_order"]
CONTROL_FIELDS = ["game_name", "game_size", "game_open", "verify_email", "show_news",
                  "show_babble", "show_online", "difficulty_medium_mod",
                  "difficulty_hard_mod", "drop_rate", "encounter_rate", "vendor_mode"]


def export_world():
    """Build the pack as a plain dict."""
    control = GameControl.objects.first()
    return {
        "format": FORMAT,
        "version": VERSION,
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "control": _row(control, CONTROL_FIELDS) if control else {},
        "vendors": [_row(v, VENDOR_FIELDS) for v in Vendor.objects.all()],
        "spells": [_row(s, SPELL_FIELDS) for s in Spell.objects.all()],
        "monsters": [_row(m, MONSTER_FIELDS) for m in Monster.objects.all()],
        "items": [_row(i, ITEM_FIELDS) for i in Item.objects.all()],
        "drops": [_row(d, DROP_FIELDS) for d in Drop.objects.all()],
        "levels": [
            dict(_row(t, LEVEL_FIELDS), spell_learned_id=t.spell_learned_id)
            for t in LevelTier.objects.all()
        ],
        "towns": [
            dict(
                _row(t, TOWN_FIELDS),
                shop_item_ids=sorted(t.shop_items.values_list("id", flat=True)),
                vendor_slugs=sorted(t.vendors.values_list("slug", flat=True)),
                sections=[
                    {"heading": sec.heading, "body": sec.body,
                     "sort_order": sec.sort_order, "is_active": sec.is_active}
                    for sec in t.sections.all()
                ],
            )
            for t in Town.objects.all()
        ],
    }


def write_pack(path, indent=2):
    data = export_world()
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=indent, ensure_ascii=False)
    return data


# ── import ──────────────────────────────────────────────────────────────────
def _check(pack):
    if pack.get("format") != FORMAT:
        raise ValueError(f"Not a Dragon Knight world pack (format={pack.get('format')!r}).")
    if int(pack.get("version", 0)) > VERSION:
        raise ValueError(
            f"Pack version {pack['version']} is newer than this game understands ({VERSION})."
        )


CONTENT_MODELS = [LevelTier, Drop, Monster, Item, Spell, TownSection, Town, Vendor]


@transaction.atomic
def import_world(pack, replace=False):
    """Load a pack. With replace=True existing content is cleared first.

    Player records are never touched here, but note that clearing content does
    affect them indirectly: equipped gear is nulled and matching bag rows are
    removed by the database's own cascade rules.
    """
    _check(pack)
    counts = {}

    if replace:
        for model in CONTENT_MODELS:
            model.objects.all().delete()

    for row in pack.get("spells", []):
        Spell.objects.update_or_create(id=row["id"], defaults={
            k: v for k, v in row.items() if k != "id"})
    counts["spells"] = Spell.objects.count()

    for row in pack.get("items", []):
        Item.objects.update_or_create(id=row["id"], defaults={
            k: v for k, v in row.items() if k != "id"})
    counts["items"] = Item.objects.count()

    for row in pack.get("drops", []):
        Drop.objects.update_or_create(id=row["id"], defaults={
            k: v for k, v in row.items() if k != "id"})
    counts["drops"] = Drop.objects.count()

    for row in pack.get("monsters", []):
        Monster.objects.update_or_create(id=row["id"], defaults={
            k: v for k, v in row.items() if k != "id"})
    counts["monsters"] = Monster.objects.count()

    for row in pack.get("vendors", []):
        data = {k: v for k, v in row.items() if k not in ("id", "slug")}
        Vendor.objects.update_or_create(slug=row["slug"], defaults=data)
    counts["vendors"] = Vendor.objects.count()

    for row in pack.get("levels", []):
        data = {k: v for k, v in row.items() if k not in ("char_class", "level")}
        LevelTier.objects.update_or_create(
            char_class=row["char_class"], level=row["level"], defaults=data)
    counts["levels"] = LevelTier.objects.count()

    for row in pack.get("towns", []):
        item_ids = row.get("shop_item_ids", [])
        vendor_slugs = row.get("vendor_slugs", [])
        sections = row.get("sections", [])
        data = {k: v for k, v in row.items()
                if k not in ("id", "shop_item_ids", "vendor_slugs", "sections")}
        town, _ = Town.objects.update_or_create(id=row["id"], defaults=data)
        town.shop_items.set(Item.objects.filter(id__in=item_ids))
        town.vendors.set(Vendor.objects.filter(slug__in=vendor_slugs))
        if sections:
            town.sections.all().delete()
            for sec in sections:
                TownSection.objects.create(town=town, **sec)
    counts["towns"] = Town.objects.count()

    control_row = pack.get("control")
    if control_row:
        GameControl.objects.update_or_create(id=1, defaults=control_row)
    counts["control"] = GameControl.objects.count()

    return counts


def read_pack(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)
