# Generated by Django 5.1.15 on 2026-07-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_monster_level', models.PositiveIntegerField(help_text='Only monsters at or above this level can drop it (original: mlevel).')),
                ('drop_type', models.PositiveIntegerField(default=0)),
                ('attribute1', models.CharField(blank=True, max_length=30)),
                ('attribute2', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['min_monster_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='Dragon Knight', max_length=50)),
                ('game_size', models.PositiveIntegerField(default=250, help_text='Map half-extent from origin.')),
                ('game_open', models.BooleanField(default=True)),
                ('verify_email', models.BooleanField(default=False)),
                ('show_news', models.BooleanField(default=True)),
                ('show_babble', models.BooleanField(default=True)),
                ('show_online', models.BooleanField(default=True)),
                ('difficulty_medium_mod', models.FloatField(default=1.2)),
                ('difficulty_hard_mod', models.FloatField(default=1.5)),
            ],
            options={
                'verbose_name': 'game control',
                'verbose_name_plural': 'game control',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(choices=[(1, 'Weapon'), (2, 'Armor'), (3, 'Shield')])),
                ('name', models.CharField(max_length=30)),
                ('buy_cost', models.PositiveIntegerField(default=0)),
                ('power', models.PositiveIntegerField(default=0, help_text='Attack power for weapons; defense power for armor/shields.')),
                ('special', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['slot', 'power'],
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_hp', models.PositiveIntegerField()),
                ('max_damage', models.PositiveIntegerField()),
                ('armor', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField(help_text='Tier; drives where it spawns and what it can drop.')),
                ('max_exp', models.PositiveIntegerField()),
                ('max_gold', models.PositiveIntegerField()),
                ('immune', models.IntegerField(choices=[(0, 'None'), (1, 'Immune to damage magic'), (2, 'Immune to sleep')], default=0)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mp_cost', models.PositiveIntegerField()),
                ('effect', models.IntegerField(choices=[(1, 'Heal'), (2, 'Damage'), (3, 'Sleep'), (4, 'Buff: Damage'), (5, 'Buff: Defense')])),
                ('attribute', models.PositiveIntegerField(help_text='Meaning depends on effect: HP healed, max damage, sleep turns, or % buff.')),
            ],
            options={
                'ordering': ['effect', 'mp_cost'],
            },
        ),
        migrations.CreateModel(
            name='BabbleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babbles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('last_reply_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='game.forumpost')),
            ],
            options={
                'ordering': ['-last_reply_at'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('inn_price', models.PositiveIntegerField(default=0, help_text='Cost to fully heal at the inn.')),
                ('map_price', models.PositiveIntegerField(default=0)),
                ('travel_points', models.PositiveIntegerField(default=0)),
                ('shop_items', models.ManyToManyField(blank=True, related_name='sold_in_towns', to='game.item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=30)),
                ('char_class', models.IntegerField(choices=[(1, 'Mage'), (2, 'Warrior'), (3, 'Paladin')])),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('current_action', models.CharField(choices=[('in_town', 'In Town'), ('exploring', 'Exploring'), ('fighting', 'Fighting')], default='in_town', max_length=20)),
                ('current_monster_hp', models.PositiveIntegerField(default=0)),
                ('current_monster_sleep', models.PositiveIntegerField(default=0, help_text='Turns remaining asleep.')),
                ('current_monster_immune', models.IntegerField(choices=[(0, 'None'), (1, 'Immune to damage magic'), (2, 'Immune to sleep')], default=0)),
                ('uber_damage', models.PositiveIntegerField(default=0, help_text='Active % damage buff this fight.')),
                ('uber_defense', models.PositiveIntegerField(default=0, help_text='Active % defense buff this fight.')),
                ('current_hp', models.IntegerField(default=15)),
                ('current_mp', models.IntegerField(default=0)),
                ('current_tp', models.IntegerField(default=10)),
                ('max_hp', models.PositiveIntegerField(default=15)),
                ('max_mp', models.PositiveIntegerField(default=0)),
                ('max_tp', models.PositiveIntegerField(default=10)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('gold', models.PositiveBigIntegerField(default=100)),
                ('exp_bonus', models.IntegerField(default=0, help_text='Percent bonus to exp gained.')),
                ('gold_bonus', models.IntegerField(default=0, help_text='Percent bonus to gold gained.')),
                ('strength', models.PositiveIntegerField(default=5)),
                ('dexterity', models.PositiveIntegerField(default=5)),
                ('attack_power', models.PositiveIntegerField(default=5)),
                ('defense_power', models.PositiveIntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
                ('pending_drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.drop')),
                ('accessory1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('accessory2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('accessory3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('shield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('current_monster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.monster')),
                ('known_spells', models.ManyToManyField(blank=True, related_name='known_by', to='game.spell')),
                ('unlocked_towns', models.ManyToManyField(blank=True, related_name='unlocked_by', to='game.town')),
            ],
            options={
                'ordering': ['char_name'],
            },
        ),
        migrations.CreateModel(
            name='LevelTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_class', models.IntegerField(choices=[(1, 'Mage'), (2, 'Warrior'), (3, 'Paladin')])),
                ('level', models.PositiveIntegerField()),
                ('exp_required', models.PositiveIntegerField(help_text='Cumulative experience to reach this level.')),
                ('hp_gain', models.PositiveIntegerField(default=0)),
                ('mp_gain', models.PositiveIntegerField(default=0)),
                ('tp_gain', models.PositiveIntegerField(default=0)),
                ('strength_gain', models.PositiveIntegerField(default=0)),
                ('dexterity_gain', models.PositiveIntegerField(default=0)),
                ('spell_learned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_at_tiers', to='game.spell')),
            ],
            options={
                'ordering': ['char_class', 'level'],
                'constraints': [models.UniqueConstraint(fields=('char_class', 'level'), name='unique_class_level')],
            },
        ),
        migrations.AddConstraint(
            model_name='town',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_town_coords'),
        ),
    ]
