# Generated by Django 5.1.15 on 2026-07-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='accessory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.drop'),
        ),
        migrations.AlterField(
            model_name='character',
            name='accessory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.drop'),
        ),
        migrations.AlterField(
            model_name='character',
            name='accessory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.drop'),
        ),
    ]
