# Generated by Django 5.1.15 on 2026-07-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_character_accessory1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
