# Generated by Django 5.1.15 on 2026-07-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_monster_max_hp',
            field=models.PositiveIntegerField(default=0, help_text="The monster's rolled starting HP, for the enemy health bar."),
        ),
        migrations.CreateModel(
            name='VisitedTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_tiles', to='game.character')),
            ],
            options={
                'indexes': [models.Index(fields=['character', 'latitude', 'longitude'], name='game_visite_charact_3cad1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('character', 'latitude', 'longitude'), name='unique_visited_tile')],
            },
        ),
    ]
