# Generated by Django 5.1.15 on 2026-07-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_current_monster_max_hp_visitedtile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecontrol',
            name='drop_rate',
            field=models.PositiveIntegerField(default=30, help_text='Loot drop chance after a victory: 1 in N. Lower = more drops (1 = every kill).'),
        ),
        migrations.AddField(
            model_name='gamecontrol',
            name='encounter_rate',
            field=models.PositiveIntegerField(default=5, help_text='Random encounter chance per tile travelled: 1 in N. Lower = more fights.'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.character')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.drop')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.item')),
            ],
            options={
                'ordering': ['acquired_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('drop__isnull', True), ('item__isnull', False)), models.Q(('drop__isnull', False), ('item__isnull', True)), _connector='OR'), name='inventory_item_xor_drop')],
            },
        ),
    ]
