# Generated by Django 5.1.15 on 2026-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamecontrol_drop_rate_gamecontrol_encounter_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('kind', models.IntegerField(choices=[(1, 'Weapons'), (2, 'Armor & shields'), (3, 'Enchanted goods'), (4, 'Maps'), (5, 'General store')])),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gamecontrol',
            name='vendor_mode',
            field=models.IntegerField(choices=[(1, 'By stock — a vendor appears if the town has goods for it'), (2, 'Assigned — each town lists exactly the vendors you choose')], default=1, help_text='How each town decides which shop counters to show.'),
        ),
        migrations.AddField(
            model_name='town',
            name='vendors',
            field=models.ManyToManyField(blank=True, help_text="Used when the vendor mode is 'Assigned'. Ignored in 'By stock' mode.", related_name='towns', to='game.vendor'),
        ),
    ]
