# Generated by Django 5.1.15 on 2026-07-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_vendor_gamecontrol_vendor_mode_town_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bank_gold',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamecontrol',
            name='bank_slots',
            field=models.PositiveIntegerField(default=20, help_text='How many items a character may store in the bank. 0 means unlimited.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.IntegerField(choices=[(1, 'Bag'), (2, 'Bank vault')], default=1),
        ),
    ]
