# Generated by Django 5.1.15 on 2026-07-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character_bank_gold_gamecontrol_bank_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True, help_text='Flavour text shown on the board.')),
                ('objective', models.IntegerField(choices=[(1, 'Slay monsters'), (2, 'Reach a level'), (3, 'Visit a town')], default=1)),
                ('target_level', models.PositiveIntegerField(default=0, help_text='Reach-level quests: the level required.')),
                ('required_count', models.PositiveIntegerField(default=1, help_text='Slay quests: how many kills are needed.')),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('reward_gold', models.PositiveIntegerField(default=0)),
                ('reward_exp', models.PositiveIntegerField(default=0)),
                ('repeatable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to retire without deleting.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('giver_town', models.ForeignKey(blank=True, help_text="Which town's board offers it. Leave empty to offer it everywhere.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='game.town')),
                ('reward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_rewards', to='game.item')),
                ('target_monster', models.ForeignKey(blank=True, help_text='Slay quests: which monster. Leave empty to count any monster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='game.monster')),
                ('target_town', models.ForeignKey(blank=True, help_text='Visit quests: which town to reach.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_targets', to='game.town')),
            ],
            options={
                'ordering': ['sort_order', 'min_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'In progress'), (2, 'Ready to hand in'), (3, 'Completed')], default=1)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='game.character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.quest')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['character', 'state'], name='game_charac_charact_cfa3ca_idx')],
            },
        ),
    ]
