# Generated by Django 5.1.15 on 2026-07-18 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_quest_characterquest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='game.town')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
