# Generated by Django 5.1.15 on 2026-07-19 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_townsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='towns/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Only the first active image is shown.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.town')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
